### ISSUE TITLE
Problemas ao compilar/rodar projeto. 

### ISSUE THREAD

**Issue by nekelpatrick** [kevinkouketsu/Wyd2Client#2]
Olá. Sei que já tem um tempo que este projeto foi parado, mas estive procurando uma solução para simular um cliente e sua solução é literalmente tudo o que eu preciso. Tentei buildar utilizando Visua Studio mesmo, e a princípio parece que faltam alguns arquivos. 

- ItemList.csv 
- ItemEffect.h
- talvez SkillData.csv tb

`Exceção gerada: 'System.IO.FileNotFoundException' em mscorlib.dll
Ocorreu uma exceção sem tratamento do tipo "System.IO.FileNotFoundException" em mscorlib.dll
Não foi possível localizar o arquivo 'C:\Users\xxxx\Source\Repos\Wyd2ClientRepo\Wyd2Client\bin\Debug\ItemEffect.h'.

O programa "[30580] Wyd2.Client.exe" foi fechado com o código 3221225786 (0xc000013a).
`

Por onde eu deveria começar?

Edit: _consegui rodar o projeto simplesmente ignorando os arquivos faltantes, mas ele não funcionou como esperado. Rodei um servidor versão 7662, e o cliente até consegue se conectar, mas é incapaz de se mover ou enviar mensagens. A UI do cliente é atualizada como se o player tivesse se movido, porém nada acontece ingame. Curiosamente, o cliente consegue ler mensagens e ver dados em tempo real._

`        public void Movement(ushort clientId, MPosition Current, MPosition Destiny, uint moveType, uint Speed)
        {
            try
            {
                var movement = new MMovePacket(clientId, Current, Destiny, moveType, Speed);

                Console.WriteLine($"Preparing to send movement packet: ClientId={clientId}, From={Current}, To={Destiny}, Type={moveType}, Speed={Speed}");
                byte[] packetBytes = W2Marshal.GetBytes(movement);
                if (packetBytes == null || packetBytes.Length == 0)
                {
                    Console.WriteLine("Failed to serialize the movement packet, check W2Marshal.GetBytes implementation.");
                    return;
                }

                Connection.Send(packetBytes);
                Console.WriteLine("Movement packet sent successfully.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error sending movement packet: {ex.Message}");
                Console.WriteLine($"StackTrace: {ex.StackTrace}");
            }
        }
`

Com esse trecho de código, eu recebo o seguinte log:
![image](https://github.com/kevinkouketsu/Wyd2Client/assets/69636803/41e7ba86-6531-4358-8ab2-9230b4bf77de)

**Comment by kevinkouketsu** [comment]
Dependendo do servidor, pode ter mudado alguma coisa em relação a estrutura do pacote, no idea. Lembro que foi feito para o servidor do global, não sei se o servidor que está tentando o pacote é o mesmo.
De qualquer forma, existe um bot feito por outra pessoa bem superior a esse.

https://github.com/DwarfDev/WYD.Frame

**Comment by nekelpatrick** [comment]
@kevinkouketsu voce conseguiu rodar o projeto do Dwarf na sua máquina? confesso que tive problemas com esse repo tbm kkkk

**Comment by kevinkouketsu** [comment]
Nunca nem clonei o repositório. Só indiquei por saber que ele existe mesmo.
